#!/usr/bin/env bash

PYTHON="${PYTHON:-python}"
SPEEDS=( 100000 400000 1000000 )

if ! type asdf &>/dev/null; then
	source ~/.asdf/asdf.sh
fi

set -exuo pipefail

"$PYTHON" -m unittest discover

for speed in "${SPEEDS[@]}"; do
	"$PYTHON" -m main build -s "$speed"
done

(
	trap 'buildkite-agent artifact upload main.vcd' ERR

	for speed in "${SPEEDS[@]}"; do
		"$PYTHON" -m main sim start -Gs "$speed"
	done
)

# "$PYTHON" -m main formal
