#!/usr/bin/env bash

PYTHON="${PYTHON:-python}"
BOARDS=( icebreaker orangecrab )
SPEEDS=( 100000 400000 )

if ! type asdf &>/dev/null; then
	source ~/.asdf/asdf.sh
fi

set -euo pipefail

echo "+++ Unit tests"

(
	trap 'buildkite-agent artifact upload "build/*.vcd"' ERR
	
	env CI=1 "$PYTHON" . test
)


for board in "${BOARDS[@]}"; do
	for speed in "${SPEEDS[@]}"; do
		echo "--- Building $board @ $speed"
		"$PYTHON" . build "$board" -s "$speed"
	done
done

for opts in "-c" "-cfi"; do
	echo "--- Building Virtual SH1107 ($opts)"
	"$PYTHON" . vsh "$opts"
done

echo "--- Formal verification"
"$PYTHON" . formal

echo "+++ All passed."
